### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by akaszynski** [pyansys/pysystem-coupling#49]
Let's consider the following before we release:
- [x] Improve documentation. I've created a CNAME for system coupling at https://systemcoupling.docs.pyansys.com/ and made the docs available (internally), but we still need:
  - [x] Enable documentation build.
  - [x] CNAME for system coupling at https://systemcoupling.docs.pyansys.com/.
  - [x] Update `gh-pages` to use the latest `ansys-sphinx-theme`
  - [x] Add examples section
  - [x] Add user guide section
  - [x] Enable multi-version documentation
- [x] Library refactor
  - [x] Move to `pyproject.toml`
  - [x] Migrate tools configuration to `pyproject.toml`
  - [x] Update to latest [pyansys/actions](https://github.com/pyansys/actions)
  - [x] Update to the best practices outlined in https://dev.docs.pyansys.com/
- [x] Security
  - [x] Protect `main` branch
  - [x] Block outside contributors from triggering workflows without approval
  - [x] Protect tags

### Post-Release

- [x] Prepare for PyPI package release
  - [x] Prepare release workflow
  - [x] Plan on using the global pypi token, then overriding it with a package scoped token after release
  - [x] Upload to [codecov](https://app.codecov.io/gh)
